/* zh-TW (Taiwan) value map for v14 delta keys; wording aligned with zh-tw.json */
"use strict";

module.exports = {
  "1 Round": "1 回合",
  "1 Round Ago": "1 回合前",
  "1 Turn": "1 輪",
  "1 Turn Ago": "1 輪前",
  "12pt": "12pt",
  "2 Rounds": "2 回合",
  "2 Rounds Ago": "2 回合前",
  "2 Turns": "2 輪",
  "2 Turns Ago": "2 輪前",
  "<Multiple Values>": "<多個數值>",
  "A 2D grid offset must have two integer coordinates, which are separated by a dot.":
    "二維網格偏移必須有兩個整數座標，並以句點分隔。",
  "A 3D grid offset must have three integer coordinates, which are separated by dots.":
    "三維網格偏移必須有三個整數座標，並以句點分隔。",
  'A Drawing that represents an "Object" is rendered in the Primary Canvas Group and is affected by lighting and fog of war exploration. One that conveys "Information" is rendered in the Interface Group and is visible to all players unless hidden.':
    "代表「物件」的繪圖會在主畫布群組中繪製，並受光照與戰爭迷霧探索影響。代表「資訊」的繪圖則繪製在介面群組中，除非隱藏，否則所有玩家皆可見。",
  "A duration in {units} will be treated as having a value of no greater than one.":
    "以 {units} 表示的持續時間將視為數值不大於 1。",
  "A grid-based shape follows the grid's distance rules, as defined by the Grid Diagonals game setting.":
    "基於網格的形狀遵循網格距離規則，如遊戲設定「網格對角線」所定義。",
  "Action Bar": "動作列",
  Activate: "啓動",
  "Active Only": "僅在場景啓動時",
  "Adaptive Attenuation": "自適應衰減",
  "Adaptive Luminance": "自適應亮度",
  Add: "新增",
  "Add Grid Offset": "新增網格偏移",
  "Add Level": "新增樓層",
  "Advanced Filter": "進階篩選",
  "Advanced Filters. Right-click to clear.":
    "進階篩選。右鍵以清除。",
  "After base-data attributes are initialized, but before derived data is prepared":
    "在基礎資料屬性初始化之後、衍生資料準備之前",
  "After derived-data attributes are computed": "在衍生資料屬性計算之後",
  "Allow Tokens that move into the Region to move to another Level the Region is included in.":
    "允許移入此區域的 Token 移動到該區域所屬的另一個樓層。",
  "Allow users with this role to create regions.": "允許此角色的使用者建立區域。",
  "Alpha Threshold": "Alpha 閾值",
  Always: "總是",
  "Always for Observers": "觀察者永遠可見",
  "An optional name to help identify the Tile.": "可選名稱，用於辨識此圖磚。",
  "An optional name to help identify the drawing.": "可選名稱，用於辨識此繪圖。",
  "An optional name to help identify the light source.": "可選名稱，用於辨識此光源。",
  "An optional name to help identify the sound.": "可選名稱，用於辨識此音效。",
  "An update is available for {title} but it may not be installed because it requires unknown core software version {vmin}.":
    "{title} 有可用更新，但可能無法安裝，因為需要未知的核心軟件版本 {vmin}。",
  Anchor: "錨點",
  Angle: "角度",
  Any: "任意",
  Appearance: "外觀",
  Apply: "套用",
  "Apply Active Effect": "套用啟用效果",
  "Apply Active Effects to Tokens while they are within the Region.":
    "在 Token 位於區域內時對其套用啟用效果。",
  "Are You Sure?": "你確定嗎？",
  "Are you sure you want to exit the Foundry Virtual Tabletop game?":
    "你確定要離開 Foundry Virtual Tabletop 遊戲嗎？",
  "Ascend Vertically": "垂直上升",
  "Attached Token": "附著的 Token",
  "Attribute Key": "屬性鍵",
  Audio: "音訊",
  Author: "作者",
  "Autoplay Video": "自動播放影片",
  Background: "背景",
  "Background Elevation": "背景高度",
  Base: "基礎",
  "Base Environment": "基礎環境",
  "Behaves as the base environmental settings, but applies as the scene's darkness level gets closer to 1.":
    "行為與基礎環境設定相同，但會隨場景黑暗程度接近 1 而套用。",
  "Bewitching Wave": "魅惑波紋",
  "Black Hole": "黑洞",
  "Blank World": "空白世界",
  "Blind to Gamemasters": "對 GM 隱藏",
  Bottom: "底部",
  "Bottom and Top": "底部與頂部",
  "Bring to Front / Send to Back": "移到最前／送到最後",
  Cancel: "取消",
  "Cancel World Creation": "取消建立世界",
  Caption: "標題",
  Center: "中央",
  "Change Level": "切換樓層",
  "Choose the Levels in which inclusion applies. An empty selection applies inclusion to all Levels.":
    "選擇套用包含關係的樓層。若未選取任何項目，則套用到所有樓層。",
  "Choose the placement of the Token inside the destination Region.":
    "選擇 Token 在目的地區域內的位置。",
  Chroma: "色度",
  Circle: "圓形",
  Clear: "清除",
  "Clear All Owned Objects": "清除所有擁有的物件",
  "Clear Hotbar": "清除快捷列",
  "Clear Initiative": "清除先攻",
  "Clear Movement History": "清除移動紀錄",
  "Clear all assigned Macros from your hotbar?": "要清除快捷列上所有已指派的巨集嗎？",
  'Cleared movement history for Token "{name}".': '已清除 Token「{name}」的移動紀錄。',
  Clone: "複製",
  Close: "關閉",
  "Close Main Menu": "關閉主選單",
  Collapse: "摺疊",
  Color: "顏色",
  "Color Burn": "色彩加深",
  Combat: "戰鬥",
  "Combat Encounters": "戰鬥遭遇",
  "Combat End": "戰鬥結束",
  "Combat Start": "戰鬥開始",
  Combatant: "戰鬥參與者",
  "Combatant Status": "戰鬥參與者狀態",
  'Compendium ID "{id}" copied to clipboard.': '合集 ID「{id}」已複製到剪貼簿。',
  Cone: "圓錐",
  Configure: "設定",
  "Configure the appearance of the grid lines.": "設定網格線的外觀。",
  "Configure the set of other Levels which are fully or partially visible from this one.":
    "設定從此樓層可完整或部分看見的其他樓層。",
  "Configure whether the shapes of this Region are constrained by walls.":
    "設定此區域的形狀是否受牆壁約束。",
  "Configure whether to display measurements for the Region.":
    "設定是否顯示此區域的測量資訊。",
  "Configure whether to highlight the true shapes or the grid spaces covered by the Region.":
    "設定要高亮真實形狀，還是區域覆蓋的網格空間。",
  Confirm: "確認",
  Continue: "繼續",
  "Control a group of Walls which define the boundary of your desired shape.":
    "控制一組定義目標形狀邊界的牆。",
  'Controls Fog of War mode: "None" disables exploration (tokens only see what they currently can), "Individual" tracks exploration separately for each user, and "Shared" uses a single exploration state contributed to by all users.':
    '控制戰爭迷霧模式：「無」會停用探索（Token 僅能看見目前可見範圍）；「個別」為每位使用者分別記錄探索；「共用」則由所有使用者貢獻單一探索狀態。',
  Coordinates: "座標",
  "Copied Region shape.": "已複製區域形狀。",
  "Copy Compendium ID": "複製合集 ID",
  "Copy Document UUID": "複製文件 UUID",
  "Covered Grid Spaces": "覆蓋的網格空間",
  "Create Active Effect": "建立啟用效果",
  "Create Combatant": "建立戰鬥參與者",
  "Create Drawing": "建立繪圖",
  "Create Regions": "建立區域",
  "Create Shapes from Controlled Walls": "由受控牆建立形狀",
  "Create {name}": "建立 {name}",
  "Creating World...": "正在建立世界…",
  "Creation successful, launching...": "建立成功，正在啟動…",
  Crosshatch: "交叉線",
  "Current Level": "目前樓層",
  Curvature: "曲率",
  Custom: "自訂",
  "Cut Region shape.": "已剪下區域形狀。",
  Darkness: "黑暗",
  "Darkness Environment": "黑暗環境",
  "Darkness-blocking Walls and Light Sources with Priority > Threshold":
    "阻擋黑暗的牆與優先度大於閾值的光源",
  Days: "天",
  Deactivate: "停用",
  Default: "預設",
  "Default Method": "預設方式",
  Defeated: "已擊敗",
  "Define Surface": "定義表面",
  "Define a surface that can restrict light, movement, sight, and sound.":
    "定義可限制光線、移動、視覺與聲音的表面。",
  Degrees: "度",
  Delete: "刪除",
  "Delete Document": "刪除文件",
  "Delete Locked Objects": "刪除已鎖定物件",
  "Delete Selected": "刪除所選",
  "Dense Smoke": "濃煙",
  "Descend Vertically": "垂直下降",
  Destinations: "目的地",
  "Detach Window": "分離視窗",
  Details: "詳細資訊",
  "Determining Scene dimensions.": "正在判斷場景尺寸。",
  "Dialog (Revealed)": "對話框（已揭露）",
  "Dialog (Unrevealed)": "對話框（未揭露）",
  Direction: "方向",
  "Display Measurements": "顯示測量",
  "Display Page Title": "顯示頁面標題",
  "Display a scrolling text above a Token when it triggers one of the subscribed events.":
    "當 Token 觸發任一訂閱事件時，在其上方顯示捲動文字。",
  "Display {document}": "顯示 {document}",
  "Displayed Name": "顯示名稱",
  Distance: "距離",
  "Do you want to move {token} to {level}?": "要將 {token} 移動到 {level} 嗎？",
  "Do you want to teleport {token} to {region} in {scene}?":
    "要將 {token} 傳送到 {scene} 的 {region} 嗎？",
  Door: "門",
  Doors: "門",
  Dots: "點點",
  "Down one level": "下移一層樓",
  Downgrade: "降級",
  "Draw Circle": "繪製圓形",
  "Draw Cone": "繪製圓錐",
  "Draw Emanation": "繪製發散",
  "Draw Line": "繪製線段",
  "Draw Ring": "繪製環形",
  "Drawing Role": "繪圖角色",
  Duration: "持續時間",
  "Duration Units": "持續時間單位",
  "Duration Value": "持續時間數值",
  "Edit Shape": "編輯形狀",
  "Edit level": "編輯樓層",
  "Effect Duration": "效果持續時間",
  "Effect Start": "效果開始",
  Effects: "效果",
  "Elevation Range": "高度範圍",
  Ellipse: "橢圓",
  Emanation: "發散",
  Empty: "空",
  "Empty Slot": "空欄位",
  "Enable/disable other Region Behaviors when one of the subscribed events occurs.":
    "當任一訂閱事件發生時，啟用／停用其他區域行為。",
  "Energy Field": "能量場",
  "Entry Title": "條目標題",
  Environment: "環境",
  Error: "錯誤",
  Errors: "錯誤",
  "Ethereal Walls": "靈體牆",
  "Execute a Macro when one of the subscribed events occurs.":
    "當任一訂閱事件發生時執行巨集。",
  "Execute a script when one of the subscribed events occurs.":
    "當任一訂閱事件發生時執行指令碼。",
  Expand: "展開",
  "Expiry Event": "到期事件",
  "Exploration Mode": "探索模式",
  "External Color Burn": "外部色彩加深",
  "External Halo": "外部光暈",
  Fade: "淡化",
  "Fairy Light": "仙靈光",
  "File Path": "檔案路徑",
  "Fill Color": "填色",
  "Fill Hole": "填補孔洞",
  "Fill Opacity": "填色不透明度",
  "Fill Texture": "填色紋理",
  "Fill Types": "填色類型",
  "Filter adventures": "篩選冒險",
  "Filter by Category": "依類別篩選",
  "Filter by Level": "依樓層篩選",
  "Filter systems": "篩選系統",
  "Filter {name}": "篩選 {name}",
  Final: "最終",
  "Fit Mode": "適配模式",
  Flat: "平面",
  "Flickering Light": "閃爍光",
  "Fog Exploration": "迷霧探索",
  "Fog exploration mode has changed. This will reload fog exploration and reset vision.":
    "迷霧探索模式已變更。將重新載入迷霧探索並重設視野。",
  "Fog of War": "戰爭迷霧",
  Folder: "資料夾",
  Font: "字型",
  "Font Color": "字型顏色",
  "Font Family": "字型",
  "Font Size": "字型大小",
  "For freehand drawing, the smoothing factor controls the amount of spline smoothing.":
    "手繪時，平滑係數控制樣條平滑程度。",
  "Force Grid": "力場網格",
  Foreground: "前景",
  "Foreground Elevation": "前景高度",
  Format: "格式",
  "Ghostly Light": "幽靈光",
  Glitch: "故障",
  "Global Illumination": "全域照明",
  "Grid Offsets": "網格偏移",
  "Grid Spaces": "網格空間",
  "Grid Units": "網格單位",
  HTML: "HTML",
  "Heading Level": "標題層級",
  Height: "高度",
  "Hexa Dome": "六角穹頂",
  Hidden: "隱藏",
  "Hidden from players": "對玩家隱藏",
  Hide: "隱藏",
  "High Absorption": "高吸收",
  "Highlight Mode": "高亮模式",
  Hole: "孔洞",
  "Hole Swirl": "孔洞旋渦",
  Hologram: "全像",
  Hours: "小時",
  Huge: "巨大",
  "If Temporary": "若為暫時",
  "If a User has visibility of this Level, they will be placed on it when the Scene is activated for the first time, or if the Scene is active when joining the game.":
    "若使用者可看見此樓層，在首次啟用場景時，或加入遊戲時場景已啟用，將被放置於此樓層。",
  "If you return to setup now, you will lose any changes you have made here.":
    "若現在返回設定，你在此所做的變更將會遺失。",
  "Image Caption": "圖片標題",
  Import: "匯入",
  "Importing Adventure": "正在匯入冒險",
  "Included in Level": "包含於樓層",
  Individual: "個別",
  Information: "資訊",
  Initial: "初始",
  "Initial Level": "初始樓層",
  Initiative: "先攻",
  "Initiative Value": "先攻值",
  "Inner Width": "內側寬度",
  Insert: "插入",
  Install: "安裝",
  "Installing dependencies": "正在安裝依賴項目",
  "Instead of a port number, a file path to a Unix domain socket can be entered. If both a port and socket are entered, the socket path will be used.":
    "可輸入 Unix domain socket 的檔案路徑以取代埠號。若同時輸入埠與 socket，將使用 socket 路徑。",
  "Internal Color Burn": "內部色彩加深",
  "Internal Halo": "內部光暈",
  Invalid: "無效",
  "Invalid font size": "無效的字型大小",
  "Invert Absorption": "反轉吸收",
  "Invisible Walls": "隱形牆",
  "Is Grid-Based": "基於網格",
  "Is Hole": "為孔洞",
  "Is Restricted": "受限制",
  "Jail, Creaky": "監獄門，吱嘎",
  "Jail, Heavy": "監獄門，沉重",
  Large: "大",
  "Legacy Coloration": "舊版著色",
  Length: "長度",
  Level: "樓層",
  "Level Visibility": "樓層可見性",
  Levels: "樓層",
  "Light Dome": "光穹",
  "Light-blocking Walls and Darkness Sources with Priority ≥ Threshold":
    "阻擋光線的牆與優先度 ≥ 閾值的黑暗來源",
  Line: "線段",
  "Line Color": "線條顏色",
  "Line Opacity": "線條不透明度",
  "Line Width": "線條寬度",
  Lists: "清單",
  "Loading adventure data...": "正在載入冒險資料…",
  Lock: "鎖定",
  "Lock Hotbar": "鎖定快捷列",
  Locked: "已鎖定",
  "Log Out": "登出",
  "Login as User": "以其他使用者登入",
  "Loop Video": "循環播放影片",
  "Low Absorption": "低吸收",
  "Magical Gloom": "魔法陰霾",
  "Main Menu": "主選單",
  "Make Hole": "挖孔",
  "Mark Defeated": "標記擊敗",
  "Measured Template Mode": "測量範本模式",
  Measurement: "測量",
  Mechanics: "機制",
  Milliseconds: "毫秒",
  Minutes: "分鐘",
  Miscellaneous: "其他",
  "Modify the movement cost of Tokens within the Region.":
    "修改區域內 Token 的移動消耗。",
  Months: "月",
  Morph: "變形",
  Move: "移動",
  "Move Down": "下移",
  "Move Down+Left": "左下移",
  "Move Down+Right": "右下移",
  "Move Left": "左移",
  "Move Right": "右移",
  "Move Shape Down": "下移形狀",
  "Move Shape Up": "上移形狀",
  "Move Up": "上移",
  "Move Up+Left": "左上移",
  "Move Up+Right": "右上移",
  "Movement, vision, and hearing": "移動、視覺與聽覺",
  "Movement, vision, and hearing unless opened": "移動、視覺與聽覺（開啟門前）",
  "Movement-blocking Walls": "阻擋移動的牆",
  Multiply: "乘算",
  "Mute Volume": "靜音",
  "Mysterious Emanation": "神秘發散",
  Name: "名稱",
  "Natural Attenuation": "自然衰減",
  "Natural Light": "自然光",
  Never: "永不",
  "Next Page": "下一頁",
  No: "否",
  "No Animation": "無動畫",
  "No Author": "無作者",
  "No Level": "無樓層",
  None: "無",
  Normal: "一般",
  "Normal Walls": "一般牆",
  "Not Included in Level": "未包含於樓層",
  "Not Rolled": "未擲骰",
  Occlusion: "遮擋",
  "Occlusion Modes": "遮擋模式",
  Offset: "偏移",
  "Only on Region Layer when unlocked": "僅在解鎖時於區域圖層顯示",
  "Operation timed out when detaching Application window. You may have a popup-blocker active.":
    "分離應用程式視窗逾時。你可能啟用了阻擋彈出式視窗。",
  Origin: "原點",
  "Outer Width": "外側寬度",
  Override: "覆寫",
  "Override Detection Mode": "覆寫偵測模式",
  "Override, brighten, or darken the Scene's Darkness Level within the Region.":
    "在區域內覆寫、提亮或調暗場景的黑暗程度。",
  "Page Category": "頁面類別",
  "Page Name": "頁面名稱",
  Palette: "調色板",
  "Pan to Combatant": "平移至戰鬥參與者",
  "Partially reveal the visible area of this elevated surface to observers below and outside of it. The revealed area depends on the angle between the observer and the surface boundary, this area decreases as the angle becomes steeper. This option is useful for roofs, balconies, or other overhead platforms.":
    "向下方與外側的觀察者部分顯示此抬高表面的可見區域。可見範圍取決於觀察者與表面邊界夾角，夾角越陡範圍越小。適用於屋頂、陽台或其他高架平台。",
  "Pasted Region shape.": "已貼上區域形狀。",
  Pattern: "圖案",
  "Pause the game when a Token is moved into the Region by a player.":
    "當玩家將 Token 移入區域時暫停遊戲。",
  Perception: "感知",
  "Permanently delete all viewed {type} objects that you own?":
    "要永久刪除你所擁有、已檢視過的所有 {type} 物件嗎？",
  Permissions: "權限",
  Phase: "階段",
  "Ping Token": "Ping Token",
  Pixels: "像素",
  "Pixels in the Tile image with alpha values below this threshold do not restrict light or weather and do not trigger hover fading.":
    "圖磚影像中 Alpha 低於此閾值的像素不會限制光線或天氣，也不會觸發懸停淡化。",
  "Pixels in the background texture with alpha values below this threshold do not restrict light or weather.":
    "背景紋理中 Alpha 低於此閾值的像素不會限制光線或天氣。",
  Placeables: "可放置物",
  Placement: "位置",
  "Play this transition animation only when the Scene is activated or when it is active after joining the game.":
    "僅在啟用場景時，或加入遊戲後場景已啟用時播放此轉場動畫。",
  Points: "點",
  Polygon: "多邊形",
  Position: "位置",
  Positioning: "定位",
  Presentation: "呈現",
  Preview: "預覽",
  "Previous Page": "上一頁",
  Priority: "優先度",
  "Priority Threshold": "優先度閾值",
  "Private to Gamemasters": "僅 GM 可見",
  "Public as Character": "以角色公開",
  "Public as User": "以使用者公開",
  Pulse: "脈動",
  "Pulsing Wave": "脈動波",
  "Quick-Start of module '{title}' failed: {message}. See the console (F12) for more details.":
    "模組「{title}」快速啟動失敗：{message}。詳見主控台（F12）。",
  Radial: "放射",
  "Radial Rainbow": "放射彩虹",
  Radius: "半徑",
  Random: "隨機",
  "Random Color": "隨機顏色",
  Ratio: "比例",
  "Re-attach Window": "重新附加視窗",
  "Re-roll Initiative": "重擲先攻",
  Rectangle: "矩形",
  "Region Animation State Changed": "區域動畫狀態已變更",
  Relative: "相對",
  "Remove All Shapes": "移除所有形狀",
  "Remove Combatant": "移除戰鬥參與者",
  "Remove Grid Offset": "移除網格偏移",
  "Remove Shape": "移除形狀",
  "Remove level": "移除樓層",
  "Replace {type}": "取代 {type}",
  "Represented Actor": "代表角色",
  "Represented Token": "代表 Token",
  "Requires Unknown Version": "需要未知版本",
  Reset: "重設",
  "Reset Defaults": "重設為預設",
  "Reset to Default Options": "重設為預設選項",
  "Restricted By": "受限於",
  Restrictions: "限制",
  "Restricts Light and Darkness": "限制光線與黑暗",
  "Restricts Movement": "限制移動",
  "Restricts Sight": "限制視覺",
  "Restricts Sound": "限制聲音",
  Result: "結果",
  "Reveal Elevated Surface": "顯露抬高表面",
  "Reveal the destination(s) of this teleporter to anyone.":
    "向所有人揭露此傳送門的目的地。",
  Revealed: "已揭露",
  "Revolving Light": "旋轉光",
  Ring: "環形",
  "Roiling Mass": "翻騰煙塵",
  Rotation: "旋轉",
  Round: "回合",
  "Round End": "回合結束",
  "Round Start": "回合開始",
  "Round {round}, Turn {turn}": "第 {round} 回合，第 {turn} 輪",
  Rounds: "回合",
  "Save and Continue": "儲存並繼續",
  Scale: "縮放",
  "Scene Properties": "場景屬性",
  "Scenes support more than one vertical level. Add a new level to convert this scene into a multi-level scene.":
    "場景可包含多個垂直樓層。新增樓層可將此場景轉為多樓層場景。",
  Seconds: "秒",
  "Secret Doors": "密門",
  "Select All": "全選",
  "Select Ambient Sounds": "選擇環境音效",
  "Select Light Sources": "選擇光源",
  "Select the destination in {scene} you want to teleport {token} to.":
    "選擇在 {scene} 中要傳送 {token} 的目的地。",
  "Select the destination you want to teleport {token} to.":
    "選擇要傳送 {token} 的目的地。",
  "Select the level you want to move {token} to.":
    "選擇要將 {token} 移動到的樓層。",
  "Self Only": "僅自己",
  Semicircle: "半圓",
  "Send Message": "傳送訊息",
  "Set Font Color": "設定字型顏色",
  "Set Font Size": "設定字型大小",
  "Setting a password for the Gamemaster account is strongly recommended.":
    "強烈建議為遊戲主持人帳號設定密碼。",
  Shape: "形狀",
  Shapes: "形狀",
  Shared: "共用",
  Sheet: "資訊卡",
  "Should the icon representing this Effect be displayed in the UI while this effect is active?":
    "此效果啟用時，是否要在介面中顯示代表圖示？",
  Show: "顯示",
  "Show Icon?": "顯示圖示？",
  "Show Video Controls": "顯示影片控制項",
  "Sight-blocking Walls and Darkness Sources with Priority ≥ Threshold":
    "阻擋視線的牆與優先度 ≥ 閾值的黑暗來源",
  "Siren Light": "警笛光",
  Size: "大小",
  Small: "小",
  "Smoke Patch": "煙塊",
  "Smoothing Factor": "平滑係數",
  Snap: "對齊",
  "Snap the destination position the Token is teleported to.":
    "將 Token 傳送後的目的地位置對齊網格。",
  Software: "軟件",
  Solid: "實線／實心",
  "Solid Wall": "實牆",
  "Sound-Reactive Pulse": "聲音反應脈動",
  "Sound-blocking Walls": "阻擋聲音的牆",
  "Star Light": "星光",
  "Start Time": "開始時間",
  Subtract: "減算",
  "Successfully installed dependencies": "已成功安裝依賴項目",
  Sunburst: "日芒",
  "Suppress weather effects within the Region.": "在區域內抑制天氣效果。",
  Surface: "表面",
  Swirl: "旋渦",
  "Swirling Fog": "旋渦霧",
  "Swirling Rainbow": "旋渦彩虹",
  "Teleport Tokens that are moved into the Region to another Region.":
    "將移入區域的 Token 傳送到另一區域。",
  "Terrain Walls": "地形牆",
  "Text Color": "文字顏色",
  "Text Label": "文字標籤",
  "Text Opacity": "文字不透明度",
  Texture: "紋理",
  "Texture Tint": "紋理染色",
  "The Region must be on the same Level as the Token it's attached to.":
    "區域必須與附著的 Token 位於同一樓層。",
  "The Token the Region is attached to. When this Token is moved, the Region is moved with it.":
    "區域附著的 Token。移動此 Token 時，區域會一併移動。",
  "The World could not be created as required dependencies were not installed.":
    "因必要依賴項目未安裝，無法建立世界。",
  "The area enclosed by the controlled Walls is empty! Make sure that the outer Walls form a closed loop and are connected endpoint to endpoint.":
    "受控牆所圍區域為空！請確認外牆形成封閉迴路且端點相連。",
  "The destination Region(s) the Token is teleported to once it is moved into this Region. If multiple destination Regions are configured, one of them is randomly selected unless a choice is allowed and either this teleporter is revealed or the User that moved the Token is a GM.":
    "Token 移入此區域後會被傳送至的目的地區域。若設定多個目的地，除非允許選擇且（此傳送門已揭露或移動 Token 的使用者為 GM），否則會隨機擇一。",
  "The distance each grid space represents on this scene, in units appropriate to the game system.":
    "此場景中每個網格空間代表的距離，單位依遊戲系統而定。",
  "The duration of the transition animation in milliseconds.":
    "轉場動畫持續時間（毫秒）。",
  "The effects that are applied to Tokens within the Region.":
    "套用於區域內 Token 的效果。",
  "The offset applied to the Scene's playable area, which is centered on the canvas by default.":
    "套用至場景可遊玩區域的偏移，預設以畫布為中心。",
  "The placed Region must be attached to a Token.": "放置的區域必須附著於 Token。",
  "The planned movement path does not meet the minimum required cost.":
    "規劃的移動路徑未達最低所需消耗。",
  "The planned movement path does not meet the minimum required distance.":
    "規劃的移動路徑未達最低所需距離。",
  "The planned movement path exceeds the maximum allowed cost.":
    "規劃的移動路徑超過最高允許消耗。",
  "The planned movement path exceeds the maximum allowed distance.":
    "規劃的移動路徑超過最高允許距離。",
  "The point in data preparation or another event a change is to be applied.":
    "資料準備過程或另一事件中套用變更的時間點。",
  "The text that is displayed in the confirmation dialog if the destination(s) are revealed or the User is a GM. {token} is replaced by the Token's name. {region} is replaced by the destination Region's name unless this teleporter has multiple destinations. {scene} is replaced by the destination Scene's name unless this teleporter has destinations in different Scenes.":
    "若目的地已揭露或使用者為 GM，確認對話框顯示的文字。{token} 會替換為 Token 名稱；{region} 會替換為目的地區域名稱（若此傳送門僅單一目的地）；{scene} 會替換為目的地場景名稱（若目的地不在不同場景）。",
  "The text that is displayed in the confirmation dialog if the destination(s) are unrevealed and the User is not a GM. {token} is replaced by the Token's name.":
    "若目的地未揭露且使用者不是 GM，確認對話框顯示的文字。{token} 會替換為 Token 名稱。",
  "The type of transition animation that is played when a Token is teleported.":
    "Token 傳送時播放的轉場動畫類型。",
  "The type of transition animation that is played when the Scene is viewed.":
    "檢視場景時播放的轉場動畫類型。",
  "There is already a Document {link} with ID <code>{id}</code> in this collection. Do you wish to replace it or create a copy?":
    "此集合中已有 ID 為 <code>{id}</code> 的文件 {link}。要取代還是建立副本？",
  "This Combatant is not visible to you.": "你看不見此戰鬥參與者。",
  "This Region can't be included in multiple Levels while it's restricted.":
    "此區域受限制時不能包含於多個樓層。",
  "This Region can't be restricted because it's included in more than one Level.":
    "此區域包含於多個樓層時無法設為受限制。",
  "This World is not ready yet. Please wait for the Gamemaster to log in and complete setup before attempting to join.":
    "此世界尚未就緒。請等待遊戲主持人登入並完成設定後再嘗試加入。",
  "This field is defined by Prototype Token Overrides and cannot be edited directly.":
    "此欄位由原型 Token 覆寫定義，無法直接編輯。",
  "This field's value is being inherited from the '{level}' level. Click here to edit it directly.":
    "此欄位值繼承自「{level}」樓層。按一下此處可直接編輯。",
  "Thumbnail Image": "縮圖",
  "Tile Anchor": "圖磚錨點",
  Time: "時間",
  Tint: "染色",
  "Toggle Unconstrained Movement": "切換無約束移動",
  "Toggle Visibility": "切換可見性",
  Token: "Token",
  Top: "頂部",
  Torch: "火炬",
  "Tour Management": "導覽管理",
  "Transition Animation": "轉場動畫",
  "Transition Duration": "轉場持續時間",
  "Transition Type": "轉場類型",
  "True Shapes": "真實形狀",
  Turn: "輪",
  "Turn End": "輪次結束",
  "Turn Start": "輪次開始",
  Turns: "輪",
  Type: "類型",
  "Unable to detach Application. You may have a popup-blocker active.":
    "無法分離應用程式。你可能啟用了阻擋彈出式視窗。",
  "Unexplored Texture": "未探索紋理",
  "Unix Socket": "Unix Socket",
  Unknown: "未知",
  "Unknown Combatant": "未知戰鬥參與者",
  Unlock: "解鎖",
  "Unlock Hotbar": "解鎖快捷列",
  Unlocked: "已解鎖",
  "Unmute Volume": "取消靜音",
  "Up one level": "上移一層樓",
  Update: "更新",
  "Update Combatant": "更新戰鬥參與者",
  "Update Combatant: {name}": "更新戰鬥參與者：{name}",
  "Update Drawing": "更新繪圖",
  Upgrade: "升級",
  "Use Default": "使用預設",
  Value: "數值",
  Video: "影片",
  "Video Volume": "影片音量",
  "View level": "檢視樓層",
  Visibility: "可見性",
  Visible: "可見",
  "Visible Levels": "可見樓層",
  "Visible to some players": "對部分玩家可見",
  Vision: "視覺",
  Vortex: "漩渦",
  "Wall Restriction": "牆限制",
  Warning: "警告",
  Warnings: "警告",
  "Water Drop": "水滴",
  Waves: "波浪",
  Weeks: "週",
  "When an occludable Token is beneath the surface, Tiles with occlusion mode set to Surface, and any foreground or background Level textures at the same elevation or higher, will be occluded.":
    "當可遮擋的 Token 在表面下方時，遮擋模式為「表面」的圖磚，以及相同或更高高度的前景或背景樓層紋理，將會被遮擋。",
  "When enabled, the palette is ignored and each shape you draw creates a new Region. Shapes cannot be added to existing Regions.":
    "啟用時會忽略調色板，你繪製的每個形狀都會建立新區域。無法將形狀加入現有區域。",
  "White Noise": "白雜訊",
  Width: "寬度",
  Wind: "風",
  Windows: "窗戶",
  X: "X",
  "X-Anchor": "X 錨點",
  "X-Origin": "X 原點",
  "X-Radius": "X 半徑",
  "X-Shift": "X 偏移",
  "X-Size": "X 尺寸",
  Y: "Y",
  "Y-Anchor": "Y 錨點",
  "Y-Origin": "Y 原點",
  "Y-Radius": "Y 半徑",
  "Y-Shift": "Y 偏移",
  "Y-Size": "Y 尺寸",
  Years: "年",
  Yes: "是",
  "You are deleting a Token that has a Region attached to it. Its attached Region(s) will be permanently deleted.":
    "你正在刪除附有區域的 Token，其附著的區域將被永久刪除。",
  "You are not allowed to place waypoints while planning this movement.":
    "規劃此移動時，你不能放置路徑點。",
  "You are not allowed to rotate the placed Token.": "你不能旋轉已放置的 Token。",
  "You are not allowed to rotate the shape of the placed Region.":
    "你不能旋轉已放置區域的形狀。",
  "You are not controlling a Region that the shape can be pasted into.":
    "你未控制可貼上形狀的區域。",
  "You are not controlling any Walls!": "你沒有控制任何牆！",
  "You must be a Gamemaster to log in as another user.":
    "你必須是遊戲主持人才能以其他使用者身分登入。",
  "You must control or configure only one or no {type} when you draw a shape!":
    "繪製形狀時，你只能控制或設定一個或零個 {type}！",
  "You must provide a title for the World before continuing.":
    "繼續前你必須為世界提供標題。",
  "You must select a Game System for the World before continuing.":
    "繼續前你必須為世界選擇遊戲系統。",
  "Z-Size": "Z 尺寸",
  all: "全部",
  authorized: "已授權",
  px: "px",
  selected: "已選",
  "{combatant} (Initiative Roll: {initiative})":
    "{combatant}（先攻擲骰：{initiative}）",
  "{document} Palette": "{document} 調色板",
  "{document} Palette [{count}]": "{document} 調色板 [{count}]",
  "{region} in {scene}": "{scene} 中的 {region}",
  "{rounds} Rounds": "{rounds} 回合",
  "{rounds} Rounds Ago": "{rounds} 回合前",
  "{turns} Turns": "{turns} 輪",
  "{turns} Turns Ago": "{turns} 輪前",
};
