name: Auto release new version

on:
  push:
    branches:
      - main

jobs:
  update-translation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2

      - name: Install jq 
        run: |
          sudo apt-get install -y jq

      - name: Download pf2_cn.zip
        run: wget https://raw.githubusercontent.com/hktrpg/foundry_zh-tw/main/module.json -O ./.github/module.json

      - name: Read version from module.json
        id: read_version
        run: |
          echo "version=$(jq -r '.version' ./.github/module.json)" >> $GITHUB_OUTPUT
          rm ./.github/module.json

      - name: Create Artifact
        id: build-zip
        run: zip -r ./.github/${{ steps.read_version.outputs.version }}/module.zip  module.json zh-tw.json

      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./.github/${{ steps.read_version.outputs.version }}/module.zip, ./.github/${{ steps.read_version.outputs.version }}/module.json"
          tag: ${{ steps.read_version.outputs.version }}
